#!/bin/sh /etc/rc.common
. /usr/share/libubox/jshn.sh
. /lib/functions.sh

START=99
USE_PROCD=1
OAFD_BIN="/usr/bin/oafd"

if [ -e /lib/ipq806x.sh ];then
        . /lib/ipq806x.sh
        dev_type="$(ipq806x_product_name)"
elif [ -e /lib/ramips.sh ];then
        . /lib/ramips.sh
        dev_type="$(ramips_product_name)"
else
        . /lib/functions.sh
        dev_type="$(product_name)"
fi

service_triggers()
{
	procd_add_reload_trigger "appfilter"
}

stop_service(){
	if [ "$dev_type" = "RE-SS-02" ];then
		killall oafd
		killall -9 oafd 2>/dev/null
		rmmod dpi_filter

		/usr/sbin/jdc_harm_rule.sh delIptables 2>/dev/null
		/usr/sbin/jdc_harm_rule.sh delIpset 2>/dev/null

		echo 1 > /sys/kernel/debug/ecm/ecm_classifier_default/accel_delay_pkts

		rm /var/dnsmasq.d/wf.conf -rf
		/etc/init.d/dnsmasq restart
	fi
}

start_service(){
	if [ "$dev_type" = "RE-SS-02" ];then
		/usr/sbin/jdc_harm_rule.sh delIptables 2>/dev/null
		/usr/sbin/jdc_harm_rule.sh delIpset 2>/dev/null
		/usr/sbin/health_access.sh 2>/dev/null

		if [ ! -d /tmp/config ];then
			mkdir /tmp/config
		fi
	
		#for flow statistics
		if [ ! -f /tmp/config/tmp_user ];then
			touch /tmp/config/tmp_user
		fi

		[ -e /opt/etc/harm_website.csv.enc ] || cp /rom/etc/harm_website.csv.enc /opt/etc

		if [ ! -f /tmp/config/oaf ];then
			cp /etc/tmp_config/oaf /tmp/config 2>/dev/null
		fi
		if [ -f /lib/modules/*/dpi_filter.ko ];then
			insmod /lib/modules/*/dpi_filter.ko
		else
			insmod dpi_filter
		fi
		rule_apply role_group reload
		rule_apply app_filter reload
		rule_apply mac_filter reload
		rule_apply url_filter reload
		procd_open_instance
		procd_set_param respawn 3600 5 0
		procd_set_param stderr 1
		procd_set_param command "$OAFD_BIN"
		procd_close_instance

		if ! grep -q "config rolegroup" /etc/config/role_group; then
			echo 1 > /sys/kernel/debug/ecm/ecm_classifier_default/accel_delay_pkts
			echo 0 > /proc/sys/oaf/protect_enable
		else 
			echo 1 > /proc/sys/oaf/protect_enable
			echo 30 > /sys/kernel/debug/ecm/ecm_classifier_default/accel_delay_pkts
		fi
	fi
}
