#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=10
STOP=98

uci_apply_defaults() {
	. /lib/functions/system.sh

	cd /etc/uci-defaults || return 0
	files="$(ls)"
	[ -z "$files" ] && return 0
	mkdir -p /tmp/.uci
	for file in $files; do
		( . "./$(basename $file)" ) && rm -f "$file"
	done
	uci commit
}

boot() {
	. /lib/ipq806x.sh

	[ -f /proc/mounts ] || /sbin/mount_root
	[ -f /proc/jffs2_bbc ] && echo "S" > /proc/jffs2_bbc
	[ -f /proc/net/vlan/config ] && vconfig set_name_type DEV_PLUS_VID_NO_PAD

	if [ "$(ipq806x_product_name)" = "RE-SS-02" -o "$(ipq806x_product_name)" = "RE-CS-07" ];then
		#usb port pull high
		devmem 0x1016000 32 0x201 && devmem 0x1016004 32 0x2
	fi

	if [ -z "$(uci -q get system.@system[0].hostname)" ];then
		if [ "$(ipq806x_product_name)" = "RE-CS-07" ];then
			uci set system.@system[0].hostname='JDBox_TaiYi'
		elif [ "$(ipq806x_product_name)" = "RE-SS-02" ];then
			uci set system.@system[0].hostname='JDBox_Athena'
		else
			uci set system.@system[0].hostname='JDBox_Arthur'
		fi
		uci commit system
	fi

	mkdir -p /var/run
	mkdir -p /var/log
	mkdir -p /var/lock
	mkdir -p /var/state
	mkdir -p /tmp/.uci
	chmod 0700 /tmp/.uci
	mkdir -p /tmp/.jail
	touch /var/log/wtmp
	touch /var/log/lastlog
	touch /tmp/resolv.conf.auto
	ln -sf /tmp/resolv.conf.auto /tmp/resolv.conf
	grep -q debugfs /proc/filesystems && /bin/mount -o noatime -t debugfs debugfs /sys/kernel/debug
	[ "$FAILSAFE" = "true" ] && touch /tmp/.failsafe

	/sbin/kmodloader

	# allow wifi modules time to settle
	sleep 1

	/sbin/wifi detect > /tmp/wireless.tmp
	[ -s /tmp/wireless.tmp ] && {
		cat /tmp/wireless.tmp >> /etc/config/wireless
	}
	rm -f /tmp/wireless.tmp

	/bin/board_detect
	uci_apply_defaults
	
	# temporary hack until configd exists
	/sbin/reload_config

	# create /dev/root if it doesn't exist
	[ -e /dev/root -o -h /dev/root ] || {
		rootdev=$(awk 'BEGIN { RS=" "; FS="="; } $1 == "root" { print $2 }' < /proc/cmdline)
		[ -n "$rootdev" ] && ln -s "$rootdev" /dev/root
	}

	# create screen config
	[ "$(ipq806x_product_name)" = "RE-SS-02" -a -z "$(uci -q get system.screen_switch)" ] && {
		uci set system.screen_switch=srceen
		uci set system.screen_switch.time='1'
		uci set system.screen_switch.uprate='1'
		uci set system.screen_switch.downrate='0'
		uci set system.screen_switch.stanum='0'
		uci set system.screen_switch.weather='0'
		uci set system.screen_switch.points='1'
		uci set system.screen_switch.enable='1'
		uci commit system
	}

	[ "$(ipq806x_product_name)" = "RE-SS-02" -a -z "$(uci -q get system.screen_switch.switch)" ] && {
		uci set system.screen_switch.switch='0'
		uci commit system
	}

	upgrade_mask=`uci -q get jd_product.upgrade.upgrade_mask`
	if [ -n "$upgrade_mask" ] && [ "$upgrade_mask" != "1" ]; then
		#更换随机mac和hostname
		/usr/sbin/jd_random_mac_and_hostname.sh 2
	fi
}
