#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=95
boot() {
	mount_root done
	rm -f /sysupgrade.tgz
	if ! grep -q /opt /proc/mounts; then
		[ $(cat /etc/init.d/mount_opt | wc -l) -eq 0 ] && cp /rom/etc/init.d/mount_opt /etc/init.d/
		. /etc/init.d/mount_opt
		mount_opt_data
	fi

	# process user commands
	#[ -f /etc/rc.local ] && {
	#	sh /etc/rc.local
	#}

	# set leds to normal state
	. /etc/diag.sh

	# Clean up file cache
	echo 3 > /proc/sys/vm/drop_caches
	set_state done
	
}
