#!/bin/sh /etc/rc.common

START=19
USE_PROCD=1
QUIET=""

#lan_ip="$(uci get network.lan.ipaddr 2>/dev/null)"
lan_ip=`ifconfig br-lan | grep "inet addr:" | awk '{print $2}' | awk -F ":" '{print $2}'`
if [ -n "$lan_ip" ];then
	#for guest network, prohibit access lan_ip,but allow 53 port
	ebtables -F
	ebtables -A INPUT -i ath11 -p ipv4 --ip-proto 17 --ip-dport 53 -j ACCEPT
	ebtables -A INPUT -i ath11 -p ipv4 --ip-dst $lan_ip -j DROP

	ipaddr=$(uci get network.lan.ipaddr 2>/dev/null)
	netmask=$(uci get network.lan.netmask 2>/dev/null)
	if [ -n "$ipaddr" -a -n "$netmask" ];then
		ebtables -A FORWARD -i ath11 -p ipv4 --ip-dst $ipaddr/$netmask -j DROP
	fi
fi

validate_firewall_redirect()
{
	uci_validate_section firewall redirect "${1}" \
		'proto:or(uinteger, string)' \
		'src:string' \
		'src_ip:cidr' \
		'src_dport:or(port, portrange)' \
		'dest:string' \
		'dest_ip:cidr' \
		'dest_port:or(port, portrange)' \
		'target:or("SNAT", "DNAT")'
}

validate_firewall_rule()
{
	uci_validate_section firewall rule "${1}" \
		'proto:or(uinteger, string)' \
		'src:string' \
		'dest:string' \
		'src_port:or(port, portrange)' \
		'dest_port:or(port, portrange)' \
		'target:string'
}

service_triggers() {
	procd_add_reload_trigger firewall	

	procd_open_validate
	validate_firewall_redirect
	validate_firewall_rule
	procd_close_validate
}

config_check() {
	#uci show firewall > /dev/null
	#[ $? != 0 ] && {
	[ -z "$(uci -q show firewall | grep firewall.user)" ] && {
		cp -f /rom/etc/config/firewall /etc/config/
		sh /rom/etc/uci-defaults/99-miniupnpd
		sh /rom/etc/uci-defaults/99-qca-nss-ecm
		sh /rom/etc/uci-defaults/system_check
		logger "firewall:restore config file"
	}
}

restart() {
	config_check
	#killall -9 fw3 2>/dev/null
	fw3 restart
}

start_service() {
	config_check
	#killall -9 fw3 2>/dev/null
	fw3 ${QUIET} start
}

stop_service() {
	#killall -9 fw3 2>/dev/null
	fw3 flush
}

reload_service() {
	#killall -9 fw3 2>/dev/null
	fw3 reload
}

boot() {
	# Be silent on boot, firewall might be started by hotplug already,
	# so don't complain in syslog.

	#clear plugin firewall rule
	/sbin/fw_clean_cmd.sh firewall

	QUIET=-q
	start
}
