#!/bin/sh /etc/rc.common
# Copyright (C) 2020 jdcloud

START=11
STOP=99
USE_PROCD=1

PROG1=/sbin/syslogd
PROG2=/sbin/klogd

start_service() {
    procd_open_instance
    procd_set_param command "$PROG1"
    #System logging utility
    #        -n              Run in foreground
    #        -R HOST[:PORT]  Log to HOST:PORT (default PORT:514)
    #        -L              Log locally and via network (default is network only if -R)
    #        -O FILE         Log to FILE (default: /var/log/messages, stdout if -)
    #        -s SIZE         Max size (KB) before rotation (default 200KB, 0=off)
    #        -b N            N rotated logs to keep (default 1, max 99, 0=purge)
    #        -l N            Log only messages more urgent than prio N (1-8)
    #        -S              Smaller output
    #        -D              Drop duplicates
    #        -f FILE         Use FILE as config (default:/etc/syslog.conf)
    procd_append_param command  -s5120 -b10 -f/etc/syslog.conf -D -n -t
    procd_set_param respawn 50 20 -1
    procd_close_instance

    procd_open_instance
    procd_set_param command "$PROG2"
    # Run in foreground
    procd_append_param command -n
    procd_set_param respawn 50 20 -1
    procd_close_instance
}


