#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
NAME=jdc_flow
PROG=/usr/sbin/jdc_flow

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 0
	procd_close_instance
}

stop_service() {
	service_stop /usr/sbin/jdc_flow
}

reload() {
	service_reload /usr/sbin/jdc_flow
}
