#!/bin/sh /etc/rc.common

START=98
USE_PROCD=1

# To start a service we need the function 'start_service'.
# stop_service is only needed when you need special things to stop your service.
#   stop_service() is called after procd killed the service.
# The service itself should run in the foreground. (Apparently
PROG='/usr/sbin/jdc_agent'

start_service() {
	procd_open_instance
	procd_set_param command $PROG

	# respawn automatically if something died, be careful if you have an alternative process supervisor
	# if process dies sooner than respawn_threshold, it is considered crashed and after 5 retries the service is stopped
	#procd_set_param respawn ${respawn_threshold:-10} ${respawn_timeout:-10}  #${respawn_retry:-5}
	#respawn_threshold: 进程启动存活小于 threshold 认为 是异常, retry +1
	#respawn_timeout: 进程死后 timeout 秒后 拉起
	#respawn_retry: retry 大于 此值 不再重试
	procd_set_param respawn 3600 5 0

	#procd_set_param env SOME_VARIABLE=funtimes  # pass environment variables to your process
	#procd_set_param limits core="unlimited"  # If you need to set ulimit for your process
	#procd_set_param file /var/etc/your_service.conf # /etc/init.d/your_service reload will restart the daemon if these files have changed
	#procd_set_param netdev dev # likewise, except if dev's ifindex changes.
	#procd_set_param data name=value ... # likewise, except if this data changes.
	#procd_set_param stdout 1 # forward stdout of the command to logd
	#procd_set_param stderr 1 # same for stderr
	#procd_set_param root root # run service as user group
	#procd_set_param pidfile /var/run/joylink.pid # write a pid file on instance start and remote it on stop
	procd_close_instance
}

