#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
NAME=jdc_evtreport
PROG=/usr/sbin/jdc_evtreport

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 0
	procd_close_instance
}

stop_service() {
	service_stop $PROG
}

reload() {
	service_reload $PROG
}
