#!/bin/sh /etc/rc.common
START=99
STOP=10

USE_PROCD=1
PROG=/sbin/jdcapp_rpc

start_service() {
	procd_open_instance
	procd_set_param command $PROG
	procd_set_param respawn 3600 5 0
	procd_close_instance
}

stop_service() {
	killall -9 jdcapp_rpc 2>/dev/null
}
