#!/bin/sh /etc/rc.common

START=98

USE_PROCD=1
NAME=jdcloud_bi
PROG=/usr/sbin/jdcloud_bi
PROG_SHELL="/sbin/jd_get_tcp_retrans.sh"

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 0
	procd_close_instance
	
	procd_open_instance
	procd_set_param command "$PROG_SHELL"
	procd_set_param respawn 3600 5 0
	procd_close_instance
}

stop_service() {
	service_stop /usr/sbin/jdcloud_bi
	service_stop $PROG_SHELL
	killall $PROG_SHELL >/dev/null 2>&1
}

reload() {
	service_reload /usr/sbin/jdcloud_bi
}
