#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=01
STOP=98

. /lib/ipq806x.sh
TIME_DURATION_1MIN=60
TIME_DURATION_5MIN=300
mount_opt_data() {
	plugin_p=$(find_mmc_part "log" 2> /dev/null)
	[ -n "$plugin_p" -a -z "$(cat /proc/mounts | grep "$plugin_p")" ] && {
		#[ "$(file -s $plugin_p | awk -F ": " '{print $2}')" == "data" ] && {
		#	mke2fs -t ext4 $plugin_p
		#	sleep 2
		#}
		[ ! -d /opt ] && rm -f /opt
		mkdir -p /opt
		#fs check
		/usr/bin/timeout $TIME_DURATION_1MIN e2fsck -y $plugin_p
		ret=$?
		[ $((ret >> 3)) -eq 1 ] && {
			logger mount_opt:$plugin_p check failed, need format!!!
			echo y | mkfs.ext4 $plugin_p
		}
		mount -t ext4 $plugin_p /opt -o noatime -o discard
		if [ -n "$(cat /proc/mounts | grep "$plugin_p")" ];then
			rm -rf /opt/syslog.*.gz 2>/dev/null
			insmod xt_cgroup
			#for storage token
			mkdir -p /opt/etc/config
			if [ -z "$(ls /opt/etc/config/)" ];then
				macddr=`factory_hm info | grep "eth1 mac" | awk -F "=" '{print $2}' | tr -d ":"`
				fid=`uci get joylink.config.feedid`
				[ -n "$macddr" -a -n "$fid" ] && cd /opt/etc/config && touch $(echo -n $macddr$fid@@@@ | md5sum | awk '{print $1}')
			fi
			#for upgrade
			mkdir -p /opt/jd-firmware
			mkdir -p /opt/downloader
			#修复离线下载导致的opt空间占满
			DEVNAME="$(echo $plugin_p | awk -F "/" '{print $3}')"
			[ -n "$DEVNAME" ] && {
				#[ -L /opt/downloader/$DEVNAME ] && rm -f /opt/downloader/$DEVNAME
				[ -n "$(ls -l /opt/downloader/$DEVNAME | grep ^d)" ] && rm -rf /opt/downloader/$DEVNAME
				DEVNAME=
			}
		else
			rmdir /opt
		fi
	}
	
	log_p=$(find_mmc_part "plugin" 2> /dev/null)
	[ -n "$log_p" -a -z "$(cat /proc/mounts | grep "$log_p")" ] && {
		#[ "$(file -s $plugin_p | awk -F ": " '{print $2}')" == "data" ] && {
		#	mke2fs -t ext4 $plugin_p
		#	sleep 2
		#}
		[ ! -d /log ] && rm -f /log
		mkdir -p /log
		[ -z "$(/sbin/block info | grep -w $log_p)" ] && echo y | mkfs.ext4 $log_p
		#fs check
		/usr/bin/timeout $TIME_DURATION_1MIN e2fsck -y $log_p
		ret=$?
		[ $((ret >> 3)) -eq 1 ] && {
			logger mount_opt:$log_p check failed, need format!!!
			echo y | mkfs.ext4 $log_p
		}
		mount -t ext4 $log_p /log -o noatime -o discard
		if [ -z "$(cat /proc/mounts | grep "$log_p")" ];then
			rmdir /log
		elif [ -d /opt -a -d /log/etc/config -o -d /log/jd-firmware ];then
			rm -rf /opt/etc
			rm -rf /opt/jd-firmware
			mv -f /log/* /opt
		fi
	}

	swap_p=$(find_mmc_part "swap" 2> /dev/null)
	[ -n "$swap_p" ] && {
		if [ "$(ipq806x_product_name)" = "jdc-ss01" ];then
			if [ -z "$(cat /proc/mounts | grep $swap_p)" ];then
				swapoff $swap_p 2>&1 >/dev/null
				[ -z "$(/sbin/block info | grep -w $swap_p)" ] && echo y | mkfs.ext4 -m 1 -E nodiscard $swap_p
				/usr/bin/timeout $TIME_DURATION_1MIN e2fsck -y $swap_p
				ret=$?
				[ $((ret >> 3)) -eq 1 ] && echo y | mkfs.ext4 -m 1 -E nodiscard $swap_p
				mkdir -p /jdc_plg
				mount -t ext4 $swap_p /jdc_plg -o noatime -o discard
			fi
		else
			mkswap $swap_p 2>&1 >/dev/null
			swapon $swap_p 2>&1 >/dev/null
		fi
	}

	storage_p=$(find_mmc_part "storage" 2> /dev/null)
	[ -n "$storage_p" ] && DEVNAME="$(echo $storage_p | awk -F "/" '{print $3}')"
	[ -n "$storage_p" ] && [ -z "$(cat /proc/mounts | grep "$storage_p")" -o -z "$(uci -q get samba.$DEVNAME.part_size)" ] && {
		#分区未初始化时，先格式化
		#[ "$(file -s $storage_p | awk -F ": " '{print $2}')" == "data" ] && {
		#	mke2fs -t ext4 $storage_p
		#	sleep 2
		#}
		#storage_p=/dev/mmcblk0p9
		[ -z "$DEVNAME" ] && DEVNAME="$(echo $storage_p | awk -F "/" '{print $3}')"
		logger mount_opt DEVNAME $DEVNAME
		[ ! -d /mnt/$DEVNAME ] && rm -f /mnt/$DEVNAME
		mkdir -p /mnt/$DEVNAME
		[ -z "$(/sbin/block info | grep -w $storage_p)" ] && echo y | mkfs.ext4 -m 1 -E nodiscard $storage_p
		#fs check
		if [ -z "$(cat /proc/mounts | grep "$storage_p")" ];then
			/usr/bin/timeout $TIME_DURATION_5MIN e2fsck -y $storage_p
			ret=$?
			[ $((ret >> 3)) -eq 1 ] && {
				disk_mode=`fw_printenv -n $DEVNAME | tr -d '\n'`
				[ "$disk_mode" != "samba" ] && echo y | mkfs.ext4 -m 1 -E nodiscard $storage_p
			}
			mount -t ext4 $storage_p /mnt/$DEVNAME -o noatime -o discard
			sleep 1
		fi
		
		if [ -n "$(cat /proc/mounts | grep "$storage_p")" ];then
			#mkdir -p /mnt/$DEVNAME/log/
			#echo *.* /mnt/$DEVNAME/log/syslog > /etc/syslog.conf
			#uci set system.@system[0].log_file='/mnt/$DEVNAME/log/syslog'
			#uci commit system

			if [ -e /mnt/$DEVNAME/.jdc_disk_mode ];then
				disk_mode=`cat /mnt/$DEVNAME/.jdc_disk_mode | tr -d '\n'`
			fi

			[ -z "$disk_mode" ] && {
				disk_mode=`fw_printenv -n $DEVNAME | tr -d '\n'`
			}

			if [ "$disk_mode" != "pcdn" -a "$disk_mode" != "samba" ];then
				disk_mode='pcdn'
			fi
			echo $disk_mode > /mnt/$DEVNAME/.jdc_disk_mode

			#删除重复创建的软链接
			[ -L /mnt/$DEVNAME/$DEVNAME ] && rm -f /mnt/$DEVNAME/$DEVNAME
			[ "$disk_mode" = "samba" -a -d /www/webdav ] && {
				#add webdav folder
				rm -f /www/webdav/$DEVNAME
				[ -z "$(ls -lR /mnt/$DEVNAME 2>/dev/null | grep ^l | awk -F "-> " '{print $2}' | grep ^/ | grep -v /mnt)" -a -z "$(ls -lR /mnt/$DEVNAME 2>/dev/null | grep ^l | awk -F "-> " '{print $2}' | grep [.][.]/)" ] && ln -s /mnt/$DEVNAME/ /www/webdav/$DEVNAME
			}

			part_size=$(df | grep /dev/$DEVNAME | awk 'NR==1{print $2}')
			[ -z "$part_size" ] && {
				sector_size=`cat /sys/bus/mmc/drivers/mmcblk/mmc0*/block/mmcblk0/size`
				part_size=$((sector_size*512))
			}
			logger mount_opt part_size $part_size
			/sbin/uci -q delete samba.$DEVNAME
			#add samba config
			section=`/sbin/uci add samba sambashare`
			/sbin/uci rename samba.$section=$DEVNAME
			/sbin/uci set samba.$DEVNAME.name=$DEVNAME
			/sbin/uci set samba.$DEVNAME.path=/mnt/$DEVNAME
			/sbin/uci set samba.$DEVNAME.part_size=$part_size
			/sbin/uci set samba.$DEVNAME.type='ext4'
			/sbin/uci set samba.$DEVNAME.read_only=no
			/sbin/uci set samba.$DEVNAME.guest_ok=yes
			/sbin/uci set samba.$DEVNAME.create_mask=777
			/sbin/uci set samba.$DEVNAME.dir_mask=777
			/sbin/uci set samba.$DEVNAME.dev='mmcblk0'
			/sbin/uci set samba.$DEVNAME.part=$DEVNAME
			/sbin/uci set samba.$DEVNAME.mode=$disk_mode
			[ -z "$(uci -q get samba.$DEVNAME.part)" ] && {
				/sbin/uci set samba.$DEVNAME.part=$DEVNAME
			}
			[ -z "$(uci -q get samba.$DEVNAME.path)" ] && {
				/sbin/uci set samba.$DEVNAME.path=/mnt/$DEVNAME
			}
			logger mount_opt part $part
			/sbin/uci commit samba
			chmod 777 /mnt/$DEVNAME
			chmod 644 /mnt/$DEVNAME/.jdc_disk_mode

			if [ "$(ipq806x_product_name)" = "jdc-ss01" ];then
				if [ -e /mnt/$DEVNAME/.swap ]; then
					swapon /mnt/$DEVNAME/.swap || {
						rm /mnt/$DEVNAME/.swap
						dd if=/dev/zero of=/mnt/$DEVNAME/.swap bs=256k count=2048 && mkswap /mnt/$DEVNAME/.swap && swapon /mnt/$DEVNAME/.swap &
					}
				else
					dd if=/dev/zero of=/mnt/$DEVNAME/.swap bs=256k count=2048 && mkswap /mnt/$DEVNAME/.swap && swapon /mnt/$DEVNAME/.swap &
				fi
			fi
		else
			rmdir /mnt/$DEVNAME
			#echo *.* /var/log/syslog > /etc/syslog.conf
			#uci set system.@system[0].log_file='/var/log/syslog'
			#uci commit system
			logger mount_opt mount $DEVNAME failed!!!
		fi
		/etc/init.d/jdc-log restart
	}
}

boot() {
	mount_opt_data
}
