#!/bin/sh /etc/rc.common

START=20
STOP=90

EXTRA_COMMANDS="${EXTRA_COMMANDS} light_reload light_reload_ezmesh  wan_reconn wan_stop"
EXTRA_WAN_RECONNECTING=/tmp/.wan_reconnecting
USE_PROCD=1

init_switch() {
	setup_switch() { return 0; }

	include /lib/network
	setup_switch
}

network_cleanup() {
	killall netifd 2&> /dev/null
}

start_service() {
	init_switch

	[ -e "usr/sbin/fst.sh" ] && /usr/sbin/fst.sh configure

	procd_open_instance
	procd_set_param command /sbin/netifd
	#procd_set_param limits core="unlimited"
	procd_set_param respawn 3600 5 0
	procd_set_param watch network.interface
	[ -e /proc/sys/kernel/core_pattern ] && {
		procd_set_param limits core="unlimited"
		echo '/tmp/%e.%p.%s.%t.core' > /proc/sys/kernel/core_pattern
	}
	procd_close_instance
	[ -f /usr/bin/lte-cm ] && {
		/usr/bin/lte-cm start
	}
}

reload_service() {
	init_switch
	ubus call network reload
	/sbin/wifi reload_legacy
}

light_reload() {
	local rv=0
	if [ "$(uci -q get system.@system[0].cap_init)" = "1" ];then
		restart
		return 0
	fi
	init_switch
	ubus call network reload || rv=1

	sleep 6 && {
		[ $(ifconfig br-lan 2>/dev/null | grep RUNNING | wc -l) -eq 0 ] && {
			ifup -w lan
		}

		[ "$(uci -q get jd_product.iptv_info.enable)" = "1" ] && {
			if [ -e /lib/ipq806x.sh ];then
				. /lib/ipq806x.sh
				dev_type="$(ipq806x_product_name)"
			fi

			if [ "$dev_type" = "RE-SS-02" ];then
				if [ "$(uci -q get network.wan.customize_wan)" = "eth0" ]; then
					ssdk_sh port autoNeg restart 5
				else
					ssdk_sh port autoNeg restart 1
				fi
			fi

			ssdk_sh port autoNeg restart 2
			ssdk_sh port autoNeg restart 3
			ssdk_sh port autoNeg restart 4
		}
	} &

	return $rv
}

light_reload_ezmesh() {
	local rv=0

	init_switch
	ubus call network reload || rv=1

	sleep 6 && {
		[ $(ifconfig br-lan 2>/dev/null | grep RUNNING | wc -l) -eq 0 ] && {
			ifup -w lan
		}

		[ "$(uci -q get jd_product.iptv_info.enable)" = "1" ] && {
			if [ -e /lib/ipq806x.sh ];then
				. /lib/ipq806x.sh
				dev_type="$(ipq806x_product_name)"
			fi

			if [ "$dev_type" = "RE-SS-02" ];then
				if [ "$(uci -q get network.wan.customize_wan)" = "eth0" ]; then
					ssdk_sh port autoNeg restart 5
				else
					ssdk_sh port autoNeg restart 1
				fi
			fi

			ssdk_sh port autoNeg restart 2
			ssdk_sh port autoNeg restart 3
			ssdk_sh port autoNeg restart 4
		}
	} &

	return $rv
}

stop_service() {
	/sbin/wifi down
	ifdown -a
	sleep 1

	[ -f /usr/bin/lte-cm ] && {
		/usr/bin/lte-cm stop
	}
	network_cleanup
}

wan_stop() {
	if [ "$(uci -q get ipv6.config.enabled)" = "0" ];then
		ifdown -w wan
	else
		ifdown -w wan
		ifdown -w wan6
	fi
}

service_running() {
	if [ ! -e "$EXTRA_WAN_RECONNECTING" ];then
		ubus -t 30 wait_for network.interface
		/sbin/wifi reload_legacy
	fi
}

validate_atm_bridge_section()
{
	uci_validate_section network "atm-bridge" "${1}" \
		'unit:uinteger:0' \
		'vci:range(32, 65535):35' \
		'vpi:range(0, 255):8' \
		'atmdev:uinteger:0' \
		'encaps:or("llc", "vc"):llc' \
		'payload:or("bridged", "routed"):bridged'
}

validate_route_section()
{
	uci_validate_section network route "${1}" \
		'interface:string' \
		'target:cidr4' \
		'netmask:netmask4' \
		'gateway:ip4addr' \
		'metric:uinteger' \
		'mtu:uinteger' \
		'table:or(range(0,65535),string)'
}

validate_route6_section()
{
	uci_validate_section network route6 "${1}" \
		'interface:string' \
		'target:cidr6' \
		'gateway:ip6addr' \
		'metric:uinteger' \
		'mtu:uinteger' \
		'table:or(range(0,65535),string)'
}

validate_rule_section()
{
	uci_validate_section network rule "${1}" \
		'in:string' \
		'out:string' \
		'src:cidr4' \
		'dest:cidr4' \
		'tos:range(0,31)' \
		'mark:string' \
		'invert:bool' \
		'lookup:or(range(0,65535),string)' \
		'goto:range(0,65535)' \
		'action:or("prohibit", "unreachable", "blackhole", "throw")'
}

validate_rule6_section()
{
	uci_validate_section network rule6 "${1}" \
		'in:string' \
		'out:string' \
		'src:cidr6' \
		'dest:cidr6' \
		'tos:range(0,31)' \
		'mark:string' \
		'invert:bool' \
		'lookup:or(range(0,65535),string)' \
		'goto:range(0,65535)' \
		'action:or("prohibit", "unreachable", "blackhole", "throw")'
}

validate_switch_section()
{
	uci_validate_section network switch "${1}" \
		'name:string' \
		'enable:bool' \
		'enable_vlan:bool' \
		'reset:bool'
}

validate_switch_vlan()
{
	uci_validate_section network switch_vlan "${1}" \
		'device:string' \
		'vlan:uinteger' \
		'ports:list(ports)'
}

service_triggers()
{
	procd_add_reload_trigger network wireless

	procd_open_validate
	validate_atm_bridge_section
	validate_route_section
	validate_route6_section
	validate_rule_section
	validate_rule6_section
	validate_switch_section
	validate_switch_vlan
	procd_close_validate
}

#restart() {
#	trap '' TERM
#	stop "$@"
#	start "$@"
#}

wan_reconn() {
	if [ -e "$EXTRA_WAN_RECONNECTING" ];then
		return 0
	fi
	touch "$EXTRA_WAN_RECONNECTING"
	netifd_pid=$(pgrep netifd)
	if [ -n "$netifd_pid" ];then
		wan_stop
	else
		stop "$@"
	fi
	sleep 1
	if [ -n "$netifd_pid" ];then
		if [ "$(uci -q get ipv6.config.enabled)" = "0" ];then
			ubus call network reload
			ubus call network.interface up '{"interface":"wan"}'
		else
			ubus call network reload
			ubus call network.interface up '{"interface":"wan"}'
			ubus call network.interface up '{"interface":"wan6"}'
		fi
	else
		start "$@"
	fi
	rm -f "$EXTRA_WAN_RECONNECTING" 2>/dev/null
}
shutdown() {
	ifdown -a
	sleep 1
}
