#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
NAME=smartqos
PROG=/usr/sbin/smartqos
EXTRA_COMMANDS=show
EXTRA_HELP="	show	Show current Qos configuration (if active)"
#[ -n "$USE_PROCD" ] && unset USE_PROCD

if [ -e /lib/ipq806x.sh ];then
	. /lib/ipq806x.sh
	dev_type="$(ipq806x_product_name)"
elif [ -e /lib/ramips.sh ];then
	. /lib/ramips.sh
	dev_type="$(ramips_product_name)"
else
	. /lib/functions.sh
	dev_type="$(product_name)"
fi

start_service() {
	if [ "$dev_type" = "RE-CP-03" ];then
		echo 1 > /sys/kernel/debug/hnat/qos_toggle
		echo "1 1" > /sys/kernel/debug/hnat/hnat_setting
	fi

	if [ "$(stat -c %F /etc/ipt_qosnss.sh)" != "regular file" ] || [ $(ls -l /etc/ipt_qosnss.sh | awk '{print $5}') -lt 100 ];then
		rm -f /etc/ipt_qosnss.sh
		cp /rom/etc/ipt_qosnss.sh /etc/
	fi

	flock -x /tmp/.smartqos.lock -c "/etc/ipt_qosnss.sh"

	qos_rule_check.sh
	for plugin_fw in $(ls /opt/etc 2>/dev/null | grep ^firewall)
	do
		. /opt/etc/$plugin_fw 2>/dev/null
	done

	if [ "$dev_type" = "RE-CP-03" ];then
		sh /sbin/mtkhnat >/dev/null 2>&1
	elif [ "$dev_type" = "RE-CS-06" ];then
		/etc/ae_mode.sh >/dev/null 2>&1
	fi

	killall -9 smartqos >/dev/null 2>&1

	if [ "$dev_type" = "RE-CP-03" ];then
		if [ "$(uci -q get smartqos.qos.qos_enable)" = "1" ]; then
			qos_upband=$(uci -q get smartqos.qos.qos_upband | awk '{print int($1)}')
			if [ $qos_upband -gt 0 ]; then
				echo 1 wrr $((qos_upband * 1000)) > /sys/kernel/debug/hnat/qdma_sch2
			else
				echo 1 wrr 2500000 > /sys/kernel/debug/hnat/qdma_sch2
			fi

			qos_downband=$(uci -q get smartqos.qos.qos_downband | awk '{print int($1)}')
			if [ $qos_downband -gt 0 ]; then
				echo 1 wrr $((qos_downband * 1000)) > /sys/kernel/debug/hnat/qdma_sch3
			else
				echo 1 wrr 2500000 > /sys/kernel/debug/hnat/qdma_sch3
			fi
		else
			echo 1 wrr 2500000 > /sys/kernel/debug/hnat/qdma_sch2
			echo 1 wrr 2500000 > /sys/kernel/debug/hnat/qdma_sch3
		fi
	fi

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 10 0
	#procd_set_param limits core="unlimited"
	procd_close_instance
}

stop_service() {
	if [ "$dev_type" = "RE-CP-03" ];then
		echo 0 > /sys/kernel/debug/hnat/qos_toggle
		echo "1 30" > /sys/kernel/debug/hnat/hnat_setting
	fi

	for iface in $(tc qdisc show | grep htb | awk '{print $5}'); do
		tc qdisc del dev $iface root 2>/dev/null
	done

	delete_chain_from_table "mangle" "qos_dev_egress"
	delete_chain_from_table "mangle" "qos_dev_egress" ip6t
	delete_chain_from_table "mangle" "qos_dev_ingress"
	delete_chain_from_table "mangle" "qos_dev_ingress" ip6t

	delete_chain_from_table "mangle" "LOCAL_RQ"
	delete_chain_from_table "mangle" "LOCAL_RQ" ip6t

	for line in $(iptables -w -t mangle -nvL qos_dev_egress --line-number 2>/dev/null | grep MARK | awk '{print $1}' | sort -nr);do
		iptables -w -t mangle -D qos_dev_egress $line
	done

	for line in $(iptables -w -t mangle -nvL qos_dev_ingress --line-number 2>/dev/null | grep MARK | awk '{print $1}' | sort -nr);do
		iptables -w -t mangle -D qos_dev_ingress $line
	done

	for line in $(ip6tables -w -t mangle -nvL qos_dev_egress --line-number 2>/dev/null | grep MARK | awk '{print $1}' | sort -nr);do
		ip6tables -w -t mangle -D qos_dev_egress $line
	done

	for line in $(ip6tables -w -t mangle -nvL qos_dev_ingress --line-number 2>/dev/null | grep MARK | awk '{print $1}' | sort -nr);do
		ip6tables -w -t mangle -D qos_dev_ingress $line
	done

	for line in $(ip6tables -w -t mangle -nvL qos_dev_egress --line-number 2>/dev/null | grep MARK | awk '{print $1}' | sort -nr);do
		ip6tables -w -t mangle -D qos_dev_egress $line
	done

	for line in $(ip6tables -w -t mangle -nvL qos_dev_ingress --line-number 2>/dev/null | grep MARK | awk '{print $1}' | sort -nr);do
		ip6tables -w -t mangle -D qos_dev_ingress $line
	done

	delete_chain_from_table "mangle" "qos_egress"
	delete_chain_from_table "mangle" "qos_egress" ip6t
	for line in $(iptables -w -t mangle -nvL qos_egress --line-number 2>/dev/null | grep MARK | awk '{print $1}' | sort -nr);do
		iptables -w -t mangle -D qos_egress $line
	done

	for line in $(ip6tables -w -t mangle -nvL qos_egress --line-number 2>/dev/null | grep MARK | awk '{print $1}' | sort -nr);do
		ip6tables -w -t mangle -D qos_egress $line
	done

	if [ "$dev_type" = "RE-CP-03" ];then
		echo 0 wrr 2500000 > /sys/kernel/debug/hnat/qdma_sch2
		echo 0 wrr 2500000 > /sys/kernel/debug/hnat/qdma_sch3
	fi
}

show()
{
	if [ "$dev_type" = "RE-CP-03" ];then
		wan_interface="$(uci get network.wan.device 2>/dev/null)"
	else
		wan_interface="$(uci get network.wan.ifname 2>/dev/null)"
		if [ "$dev_type" = "RE-CS-06" ]; then
			[ "$wan_interface" == "br-internet" ] && {
				wan_interface="eth0"
			}
		fi
	fi

	if [ -z "$wan_interface" ];then
		up_interface='br-lan'
	else
		up_interface=$wan_interface
		down_interface='br-lan'
	fi

	echo "###Egress configuration on up_interface $up_interface###"
	iptables -w -t mangle -vnL qos_egress 2>/dev/null
	tc -s qdisc show dev $up_interface
	tc -s class show dev $up_interface
	tc -s filter show dev $up_interface

	if [ -n "$down_interface" ];then
		echo "###Ingress configuration in down_interface $down_interface###"
		#iptables -t mangle -vnL qos_ingress 2>/dev/null
		iptables -w -t mangle -vnL FORWARD 2>/dev/null
		tc -s qdisc show dev $down_interface
		tc -s class show dev $down_interface
		tc -s filter show dev $down_interface
		tc -s filter show dev $down_interface parent 2:
	fi
}
