#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=99

USE_PROCD=1
PROG=/usr/sbin/telnetd

has_root_pwd() {
	local pwd=$([ -f "$1" ] && cat "$1")
	      pwd="${pwd#*root:}"
	      pwd="${pwd%%:*}"

	test -n "${pwd#[\!x]}"
}

get_root_home() {
	local homedir=$([ -f "$1" ] && cat "$1")
	homedir="${homedir#*:*:0:0:*:}"

	echo "${homedir%%:*}"
}

has_ssh_pubkey() {
	( /etc/init.d/dropbear enabled 2> /dev/null && grep -qs "^ssh-" /etc/dropbear/authorized_keys ) || \
	( /etc/init.d/sshd enabled 2> /dev/null && grep -qs "^ssh-" "$(get_root_home /etc/passwd)"/.ssh/authorized_keys )
}

start_service() {
	#if ( ! has_ssh_pubkey && \
	#     ! has_root_pwd /etc/passwd && ! has_root_pwd /etc/shadow ) || \
	#   ( ! /etc/init.d/dropbear enabled 2> /dev/null && ! /etc/init.d/sshd enabled 2> /dev/null );
	#then
	#openwrt_version:0.1.1.r2024
	version_no=`cat /rom/etc/openwrt_version | awk -F "r" '{print $2}'`
	[ $version_no -lt 1500 ] && {
		factory_hm info telnet 1
	}
	telnets="$(factory_hm info | grep telnet | awk -F "telnet=" '{print $2}')"
	if [ "$telnets" != "0" -a -z "$(factory_hm info | grep PN= | awk -F "=" '{print $2}' | grep [a-zA-Z0-9])" -a -z "$(factory_hm info | grep Private_key= | awk -F "=" '{print $2}' | grep [a-zA-Z0-9])" ] || [ "$telnets" = "1" ];then
		procd_open_instance
		procd_set_param command "$PROG" -F -l /bin/login
		#procd_set_param limits core="unlimited"
		procd_close_instance
	else
		killall -9 telnetd 2>/dev/null
	fi
}
