#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
NAME=ybbplugin
PROG=/sbin/ybbplugin

start_service() {
	prepare_env || {                                      
		logger "$NAME not started!!!"
		return                                                                         
	}
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 0
	procd_close_instance
}

prepare_env()                                                                                      
{
	#获取是否mesh子路由或AP模式
	[ "$(uci -q get system.@system[0].re_init)" = "1" -o "$(uci -q get system.@system[0].apmode_init)" = "1" ] && {
		logger "$NAME device in mesh re mode or apmode!!!"
		return 1
	}
	#获取插件开关
	[ "$(uci -q get ybbplugin.config.enable)" = "0" ] && {
		logger "$NAME switch is off!!!"
		return 1
	}
	return 0
}

stop() {
	service_stop "$PROG"
	ipset destroy ybb-iplist 2>/dev/null
	ipset destroy ybb-console 2>/dev/null
}

