#!/bin/sh
#
# Copyright (c) 2021 Qualcomm Technologies, Inc.
# All Rights Reserved.
# Confidential and Proprietary - Qualcomm Technologies, Inc.

PIPE_PATH="/var/run/ezmesh-cmd.fifo"
if [ -p $PIPE_PATH ] && [ -w $PIPE_PATH ]; then
    echo $* > $PIPE_PATH
fi
