server {
	listen       8081;
	listen 	     8082;
	listen       8083;

        listen       4431 ssl;                                                                                        
        listen       4432 ssl;                                                                                        
        listen       4433 ssl;                                                                                        
                                                                                                                      
	listen       [::]:8081 ipv6only=on;
	listen       [::]:8082 ipv6only=on;
	listen       [::]:8083 ipv6only=on;

	listen       [::]:4431 ipv6only=on;
	listen       [::]:4432 ipv6only=on;
	listen       [::]:4433 ipv6only=on;

	server_name  localhost;

        ssl_certificate /etc/nginx/ca.crt;                                                                            
        ssl_certificate_key /etc/nginx/server.key; 

	location / {
		root   /www;
		add_header Cache-Control "no-cache, no-store";
		index  health.html;

		#proxy_pass http://localhost/health.html;
		#lua_code_cache on;

		set $remoteaddr "$remote_addr";
		set $serverport "$server_port";
		set $urlhost "$host";

		#log_by_lua '
		#	local sqlite3 = require("lsqlite3")
		#
		#	local uci=require("uci")
		#	local x = uci.cursor()
		#	local lanip = x:get("network", "lan", "ipaddr")
		#	if ngx.var.urlhost == "jdcloudwifi.com" or ngx.var.urlhost == lanip then
		#		return
		#	end
		#
		#	local command = "ip neigh show 2>/dev/null | grep " .. ngx.var.remoteaddr
		#	local mac_address = nil
		#	local upper_mac = nil
		#
		#	local handle = io.popen(command)
		#	for line in handle:lines() do
		#		local parts = line:match("%w+%s+(%w+:%w+:%w+:%w+:%w+:%w+)")
		#		if parts then
		#			mac_address = parts
		#			break
		#		end
		#	end
		#	handle:close()
		#
		#	if mac_address then
		#		upper_mac = mac_address:gsub("%:", ""):upper()
		#	end
		#
		#
		#	local type = 0
		#	local proto = 0
		#
		#	if (tonumber(ngx.var.serverport) >= 8081 and tonumber(ngx.var.serverport) <= 8083 ) then
		#		type = tonumber(ngx.var.serverport) - 8080
		#		proto = 1
		#	end
		#
		#	if (tonumber(ngx.var.serverport) >= 4431 and tonumber(ngx.var.serverport) <= 4433 ) then
		#		type = tonumber(ngx.var.serverport) - 4430
		#		proto = 2
		#	end
		#
		#	local db = sqlite3.open("/etc/audit/url_info.db")
		#
		#	local sqlCreateTable = "CREATE TABLE url_harm (timestamp INTEGER NOT NULL, type INTEGER NOT NULL, mac TEXT NOT NULL, content TEXT NOT NULL, proto INTEGER NOT NULL, PRIMARY KEY (timestamp, mac, content));"
		#	local sqlInsertData = string.format("INSERT INTO url_harm VALUES (%d, %d, %q, %q, %d);", os.time(), type, upper_mac, ngx.var.urlhost, proto)
		#
		#	db:exec(sqlCreateTable)
		#	db:exec(sqlInsertData)
		#
		#	db:close()
		#';
	}
}

